export enum ControlledFormElementType {
  NUMBER = "NUMBER",
  SELECT = "SELECT",
  FILE = "FILE",
  DATE = "DATE",
  TEXT = "TEXT",
  URL = "URL",
  EMAIL = "EMAIL",
  BOOLEAN = "BOOLEAN",
  MULTI_EMAIL = "MULTI_EMAIL",
  TEXT_AREA = "TEXT_AREA",
  TEXT_EDITOR = "TEXT_EDITOR",
  MULTI_SELECT = "MULTI_SELECT",
  SEARCH = "SEARCH",
  PASSWORD = "PASSWORD",
  SLIDER = "SLIDER",
}

export enum FilterType {
  NUMBER = "NUMBER",
  SELECT = "SELECT",
  DATE = "DATE",
  TEXT = "TEXT",
  BOOLEAN = "BOOLEAN",
  MULTI_SELECT = "MULTI_SELECT",
}
